-- Persistent, token-based customer access to a public booking.
-- Raw tokens are generated by the backend and never stored in PostgreSQL.

create table public.booking_access_tokens (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null,
  appointment_id uuid not null,
  token_hash text not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  unique (token_hash),
  unique (business_id, id),
  constraint booking_access_tokens_hash_check
    check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint booking_access_tokens_expiry_check
    check (expires_at > created_at),
  constraint booking_access_tokens_appointment_fk
    foreign key (business_id, appointment_id)
    references public.appointments (business_id, id)
    on delete cascade
);

create index if not exists booking_access_tokens_appointment_idx
  on public.booking_access_tokens (
    business_id,
    appointment_id,
    expires_at desc
  );

alter table public.booking_access_tokens enable row level security;

alter table public.booking_access_tokens force row level security;

revoke all on public.booking_access_tokens from public, anon, authenticated;
